/* 
* Copyright (C) 1997, SKTC  Ltd., 
* All Rights Reserved 
* Class name: KLE.java 
* Description: The KLE process 
* 
* Modification History: 
**********************************************************
* Date		           Author		    Comments
* 04  August 2011	   ZhaoHuan			Created
**********************************************************
*/

package com.skt.oms.KLE;
import java.io.File;

/**
 * What the KLE Class dose is make the input files into a specific Lexicon.
 * It has four steps.
 * Step 1: Read some XML files and write the information of the "<content>" flag
 * 	       into the file named "content-result.xml" in the directory of KLEData.
 * Step 2: Process four XMl files generated by OLE and write the content of the
 *         "<instance>" flag into four relevant files.
 * Step 3: Use the "Lexicon-gen.data" and the 5files generated by Step 1 and 
 * 		   Step 2 to construct a general dictionary.
 * Step 4: Use the man-made "ANNODB_DC-new.xml" file to improve the lexicon in 
 *         Step 3 and get the specific field lexicon.
 */
public class KLE {
	final static boolean DEBUG = true;
	final static boolean DeleteTempFile = false;

	public static void main(String[] args)
	{		
		try
		{
			if (args.length == 2)
			{
				//The root directory and file directory of Step 1.
				String strKLEdata = "./KLEdata/";
				String strDir = args[0];
				String strFinal = args[1];
				String strConRes = strKLEdata + "content-result.xml";
				
				// The file directory of Step 2.
				String strAttr = strKLEdata + "onto/Attributes.xml";
				String strAttrRes = strKLEdata 
									+ "ontoresult/Attributes-result.xml";
				String strComp = strKLEdata + "onto/Components.xml";
				String strCompRes = strKLEdata 
									+ "ontoresult/Components-result.xml";
				String strFuncs = strKLEdata + "onto/Functions.xml";
				String strFuncsRes = strKLEdata 
									 + "ontoresult/Functions-result.xml";
				String strPhe = strKLEdata + "onto/Phenomena.xml";
				String strPheRes = strKLEdata 
								   + "ontoresult/Phenomena-result.xml";
				
				//The file directory of Step 3 and Step 4.
				String strLexGen = strKLEdata + "lexicon-gen.dat";
				String strDCTemp = strKLEdata + "lexicon-dc-temp.dat";
				String strANN = strKLEdata + "ANNODB_DC-new.xml";
				
				//KLE starts to process.
				if (DEBUG)
				{
					System.out.println("KLE starts......\n");
				}
				//Step 1:
				PreProcessContent.doDir(strDir, strConRes);
				if (DEBUG)
				{
					System.out.println("Preprocess data finish!\n");
				}
				//Step 2:
				PreProcessTarget.Do(strAttr, strAttrRes, strComp, strCompRes,
						            strFuncs, strFuncsRes, strPhe, strPheRes);
				if (DEBUG)
				{
					System.out.println("Process ontology finish!\n");
				}
				//Step 3:
				ConstructDictionary.Do(strConRes, strAttrRes, strCompRes,
						strFuncsRes, strPheRes, strLexGen, strDCTemp);
				if (DEBUG)
				{
					System.out.println("The initial lexicon finish!\n");
				}
				//Step 4:
				CreateLexicon.Do(strDCTemp, strANN, strFinal);
				if (DEBUG)
				{
					System.out.println("KLE finish!");				
				}
			
				//Choose to delete the temp files in the process.
				if (DeleteTempFile)
				{
					deleteTemp(strConRes);
					deleteTemp(strAttrRes);
					deleteTemp(strFuncsRes);
					deleteTemp(strCompRes);
					deleteTemp(strPheRes);
					deleteTemp(strDCTemp);
					
				}			
			}
			else
			{
				System.out.println("KLE needs two parameters!" + "\n");				
			}				
		}
		catch (Exception e)
		{
			e.printStackTrace();
		}
	}
	
	public static void deleteTemp(String fileDir)
	{
		File Temp = new File(fileDir);
		Temp.delete();
	}

}
